apiVersion: v1
kind: Secret
metadata:
  name: midpoint-db
  namespace: iam
type: Opaque
stringData:
  jdbc-uri: jdbc:postgresql://iam-db-rw.iam.svc.cluster.local:5432/midpoint?sslmode=require
  username: midpoint
  password: midpoint123!
