apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rws-keycloak
  namespace: iam
spec:
  image: quay.io/keycloak/keycloak:26.0
  instances: 1
  db:
    vendor: postgres
    host: iam-db-rw.iam.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
  ingress:
    enabled: true
    className: nginx
  resources:
    requests:
      cpu: "250m"
      memory: "1.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
---
# Minimal realm import to create realm 'rws' and a demo client
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rws-realm-import
  namespace: iam
spec:
  keycloakCRName: rws-keycloak
  realm:
    id: rws
    realm: rws
    displayName: RWS Demo
    enabled: true
    registrationAllowed: false
    loginWithEmailAllowed: true
    resetPasswordAllowed: true
    sslRequired: none
    webAuthnPolicy:
      rpEntityName: "RWS Demo"
      userVerificationRequirement: "required"
      createTimeout: 120000
      avoidSameAuthenticatorRegister: true
    clients:
      - clientId: rws-midpoint
        name: rws-midpoint
        protocol: openid-connect
        publicClient: true
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        redirectUris:
          - "http://*/midpoint/*"
        webOrigins:
          - "*"
