apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-charts
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
          - name: cnpg-operator
            namespace: cnpg-system
          - name: ingress-nginx
            namespace: ingress-nginx
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      source:
{{- if eq .name "cert-manager" }}
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.15.1
        helm:
          releaseName: cert-manager
          valuesObject:
            installCRDs: true
            prometheus:
              enabled: false
{{- else if eq .name "cnpg-operator" }}
        repoURL: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        targetRevision: 0.22.1
        helm:
          releaseName: cnpg
{{- else if eq .name "ingress-nginx" }}
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.10.1
        helm:
          releaseName: ingress-nginx
          valuesObject:
            controller:
              service:
                annotations:
                  # Use the built-in status endpoint exposed on the default server so Azure probes
                  # get HTTP 200s even before any ingress rules exist.
                  service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /is-dynamic-lb-initialized
                type: LoadBalancer
{{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
{{- if eq .name "cnpg-operator" }}
          - CreateNamespace=true
          - ServerSideApply=true
{{- else }}
          - CreateNamespace=true
{{- end }}
