apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: iam-cluster-settings
    behavior: merge
    envs:
      - params.env

generatorOptions:
  disableNameSuffixHash: true
