apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rws-keycloak
  namespace: iam
spec:
  image: quay.io/keycloak/keycloak:26.3.4
  instances: 1
  startOptimized: false
  additionalOptions:
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
  features:
    enabled:
      - token-exchange
  db:
    vendor: postgres
    host: iam-db-rw.iam.svc.cluster.local
    port: 5432
    database: keycloak
    schema: public
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: kc.127.0.0.1.nip.io
    strict: false
    strictBackchannel: false
  ingress:
    enabled: true
    className: nginx
    hostname: kc.127.0.0.1.nip.io
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  resources:
    requests:
      cpu: "250m"
      memory: "1.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
