apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rws-keycloak
  namespace: iam
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  image: quay.io/keycloak/keycloak:26.3.5
  instances: 1
  startOptimized: false
  additionalOptions:
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
    - name: http-management-enabled
      value: "true"
    - name: http-management-host
      value: "0.0.0.0"
    - name: cache
      value: local
  features:
    enabled:
      - token-exchange
  hostname:
    hostname: kc.4.245.81.5.nip.io
    strict: false
    strictBackchannel: false
  http:
    httpEnabled: true
  proxy:
    mode: edge
    headers: xforwarded

  db:
    vendor: postgres
    url: "jdbc:postgresql://iam-db-rw.iam.svc.cluster.local:5432/keycloak?sslmode=require"
    schema: public
    usernameSecret: { name: keycloak-db-app, key: username }
    passwordSecret: { name: keycloak-db-app, key: password }

  ingress:
    enabled: false
