apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rws-realm-import
  namespace: iam
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    iam.demo/realm-config-version: "1"
spec:
  keycloakCRName: rws-keycloak
  realm:
    id: rws
    realm: rws
    displayName: RWS Demo
    enabled: true
    registrationAllowed: false
    loginWithEmailAllowed: true
    resetPasswordAllowed: true
    sslRequired: none
    webAuthnPolicyRpEntityName: "RWS Demo"
    webAuthnPolicyUserVerificationRequirement: "required"
    webAuthnPolicyCreateTimeout: 120000
    webAuthnPolicyAvoidSameAuthenticatorRegister: true
    clients:
      - clientId: rws-midpoint
        name: rws-midpoint
        protocol: openid-connect
        publicClient: true
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        redirectUris:
          - "http://*/midpoint/*"
        webOrigins:
          - "*"
