apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: platform
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: 26.3.5
    path: kubernetes
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
