varReference:
  - kind: Application
    group: argoproj.io
    path: spec/source/repoURL
  - kind: Application
    group: argoproj.io
    path: spec/source/targetRevision
  - kind: ApplicationSet
    group: argoproj.io
    path: spec/template/spec/source/repoURL
  - kind: ApplicationSet
    group: argoproj.io
    path: spec/template/spec/source/targetRevision
