apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-addons
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            repoURL: https://charts.jetstack.io
            chart: cert-manager
            targetRevision: v1.18.2
            values:
              installCRDs: true
              prometheus:
                enabled: false
          - name: cloudnative-pg
            namespace: cnpg-system
            repoURL: https://cloudnative-pg.github.io/charts
            chart: cloudnative-pg
            targetRevision: 0.26.0
            values:
              crds:
                create: true
          - name: ingress-nginx
            namespace: ingress-nginx
            repoURL: https://kubernetes.github.io/ingress-nginx
            chart: ingress-nginx
            targetRevision: 4.13.2
            values:
              controller:
                admissionWebhooks:
                  certManager:
                    enabled: true
                service:
                  annotations:
                    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
                  type: LoadBalancer
                watchIngressWithoutClass: true
                ingressClassResource:
                  default: true
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: platform
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      source:
        repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          releaseName: '{{.name}}'
          values: |
            {{- toYaml .values | nindent 12 }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .name "cert-manager" }}
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: apiregistration.k8s.io
          kind: APIService
          jqPathExpressions:
            - .spec.caBundle
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- else if eq .name "cloudnative-pg" }}
    spec:
      source:
        helm:
          skipCrds: false
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- else }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
    {{- end }}
