apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: keycloak-db-app
    literals:
      - username=keycloak
      - password=keycloak123!
  - name: midpoint-db-app
    literals:
      - username=midpoint
      - password=midpoint123!
  - name: midpoint-admin
    literals:
      - username=administrator
      - password=admin123!
