apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

secretGenerator:
  - name: keycloak-db-app
    type: Opaque
    literals:
      - username=keycloak
      - password=keycloak123!
  - name: midpoint-db-app
    type: Opaque
    literals:
      - username=midpoint
      - password=midpoint123!
  - name: midpoint-admin
    type: Opaque
    literals:
      - username=administrator
      - password=admin123!
