apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam

resources:
  - ../../../../k8s/iam/midpoint-db-secret.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

# Keycloak consumes the CloudNativePG managed `iam-db-app` secret directly, so only
# the MidPoint credentials remain declarative here.
secretGenerator:
  - name: midpoint-db-app
    type: Opaque
    literals:
      - username=midpoint
      - password=midpoint123!
  - name: midpoint-admin
    type: Opaque
    literals:
      - username=administrator
      - password=admin123!
