apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-charts
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            repoURL: https://charts.jetstack.io
            chart: cert-manager
            targetRevision: v1.15.1
            releaseName: cert-manager
            values: '{"installCRDs":true,"prometheus":{"enabled":false}}'
          - name: cnpg-operator
            namespace: cnpg-system
            repoURL: https://cloudnative-pg.github.io/charts
            chart: cloudnative-pg
            targetRevision: 0.26.0
            releaseName: cnpg
            values: '{"crds":{"create":true}}'
          - name: ingress-nginx
            namespace: ingress-nginx
            repoURL: https://kubernetes.github.io/ingress-nginx
            chart: ingress-nginx
            targetRevision: 4.11.3
            releaseName: ingress-nginx
            valuesFiles:
              - clusters/aks/addons/ingress-nginx.values.yaml
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      source:
        repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          releaseName: '{{.releaseName}}'
          values: '{{.values}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .name "cert-manager" }}
    spec:
      ignoreDifferences:
        # cert-manager injects webhook and APIService CA bundles at runtime, so
        # ignore those controller-managed fields to keep Argo CD from reporting
        # perpetual drift.
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: apiregistration.k8s.io
          kind: APIService
          jqPathExpressions:
            - .spec.caBundle
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- else if eq .name "cnpg-operator" }}
    spec:
      source:
        helm:
          skipCrds: false
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- end }}
