apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-addons
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: $(REPO_URL)
    targetRevision: $(TARGET_REVISION)
    path: gitops/addons/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-iam
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: $(REPO_URL)
    targetRevision: $(TARGET_REVISION)
    path: gitops/iam/overlays/demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
