apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications.yaml
vars:
  - name: REPO_URL
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: cluster-git-settings
    fieldref:
      fieldPath: data.repoUrl
  - name: TARGET_REVISION
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: cluster-git-settings
    fieldref:
      fieldPath: data.targetRevision


configurations:
  - kustomizeconfig.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-git-settings
    behavior: merge
    literals:
      - repoUrl=https://github.com/your-org/iam-demo-aks-cnpg-keycloak-midpoint
      - targetRevision=main
