apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iam-db
  namespace: iam
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  superuserSecret:
    name: cnpg-superuser
    namespace: iam

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-app
        namespace: iam

  managed:
    roles:
      - name: keycloak
        login: true
        passwordSecret:
          name: keycloak-db-app
          key: password
          namespace: iam
      - name: midpoint
        login: true
        passwordSecret:
          name: midpoint-db-app
          key: password
          namespace: iam
    databases:
      - name: keycloak
        owner: keycloak
      - name: midpoint
        owner: midpoint
        extensions:
          - name: pgcrypto
          - name: pg_trgm

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: false

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "https://$(CNPG_STORAGE_ACCOUNT).blob.core.windows.net/cnpg-backups/iam-db/"
      azureCredentials:
        connectionString:
          name: cnpg-azure-backup
          key: AZURE_CONNECTION_STRING
          namespace: iam
        storageAccount:
          name: cnpg-azure-backup
          key: AZURE_STORAGE_ACCOUNT
          namespace: iam
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
        jobs: 2
