apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iam-db
  namespace: iam
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  enablePDB: true

  superuserSecret:
    name: cnpg-superuser

  storage:
    size: 20Gi
    resizeInUseVolumes: true

  affinity:
    podAntiAffinityType: preferred

  monitoring:
    enablePodMonitor: false
    customQueriesConfigMap:
      - name: cnpg-default-monitoring
        key: queries

  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: keycloak-db-app
      - name: midpoint
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: midpoint-db-app

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      encoding: UTF8
      localeCType: C
      localeCollate: C
      secret:
        name: keycloak-db-app
      postInitSQLRefs:
        configMapRefs:
          - name: cnpg-managed-databases
            key: midpoint.sql

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "https://$(CNPG_STORAGE_ACCOUNT).blob.core.windows.net/cnpg-backups/iam-db/"
      azureCredentials:
        connectionString:
          name: cnpg-azure-backup
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: cnpg-azure-backup
          key: AZURE_STORAGE_ACCOUNT
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
        jobs: 2
