apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iam-db
  namespace: iam
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      encoding: UTF8
      localeCollate: C
      localeCType: C
      postInitSQLRefs: []
      secret:
        name: keycloak-db-app

  superuserSecret:
    name: cnpg-superuser

  postgresql:
    parameters:
      # Keycloak and midPoint both request plaintext connections via their
      # strongly typed database settings. Disable server-side TLS so the
      # generated JDBC URLs connect successfully without mounting a custom CA
      # bundle into each workload.
      ssl: "off"

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: false

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "https://$(CNPG_STORAGE_ACCOUNT).blob.core.windows.net/cnpg-backups/iam-db/"
      azureCredentials:
        connectionString:
          name: cnpg-azure-backup
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: cnpg-azure-backup
          key: AZURE_STORAGE_ACCOUNT
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
        jobs: 2

  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: keycloak-db-app
      - name: midpoint
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: midpoint-db-app
