apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iam-db
  namespace: iam
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      encoding: UTF8
      localeCollate: C
      localeCType: C

  superuserSecret:
    name: cnpg-superuser

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: false

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: "https://$(CNPG_STORAGE_ACCOUNT).blob.core.windows.net/cnpg-backups/iam-db/"
      azureCredentials:
        connectionString:
          name: cnpg-azure-backup
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: cnpg-azure-backup
          key: AZURE_STORAGE_ACCOUNT
      wal:
        compression: gzip
        maxParallel: 4
      data:
        compression: gzip
        jobs: 2

  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: keycloak-db-app
          key: password
      - name: midpoint
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: midpoint-db-app
          key: password
