apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: iam
spec:
  cluster:
    name: iam-db
  name: keycloak
  owner: app
  schemas:
    - name: public
      owner: app
