apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam

resources:
  - deployment.yaml
  - precreate.yaml

configMapGenerator:
  - name: midpoint-config
    files:
      - config.xml
    options:
      disableNameSuffixHash: true
