apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam

resources:
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: midpoint-config
    files:
      - config.xml
    options:
      disableNameSuffixHash: true
  - name: midpoint-env
    literals:
      - MP_NO_ENV_COMPAT=1
      - MP_UNSET_midpoint_repository_database=1
      - MP_UNSET_midpoint_repository_jdbcUrl=1
      - MP_UNSET_midpoint_repository_hibernateHbm2ddl=1
      - MP_UNSET_midpoint_repository_initializationFailTimeout=1
      - MP_UNSET_midpoint_repository_missingSchemaAction=1
      - MP_UNSET_midpoint_repository_upgradeableSchemaAction=1
      - MP_UNSET_midpoint_repository_jdbcUsername=1
      - MP_UNSET_midpoint_repository_jdbcPassword=1
      - MP_UNSET_midpoint_repository_username=1
      - MP_UNSET_midpoint_repository_password=1
    options:
      disableNameSuffixHash: true
