apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.5/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.5/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.5/kubernetes/kubernetes.yml
  - rbac.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: keycloak-operator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak-operator
        namespace: keycloak
      spec:
        template:
          spec:
            containers:
              - name: keycloak-operator
                env:
                  - name: QUARKUS_OPERATOR_SDK_NAMESPACES
                    value: iam,keycloak
                  - name: QUARKUS_OPERATOR_SDK_GENERATE_WITH_WATCHED_NAMESPACES
                    value: iam,keycloak
