apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/${REPO_OWNER}/${REPO_NAME}
    targetRevision: HEAD
    path: k8s/apps
    kustomize:
      patchesJson6902:
        - target:
            group: networking.k8s.io
            version: v1
            kind: Ingress
            name: midpoint
            namespace: iam
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: mp.127.0.0.1.nip.io
  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: KeycloakRealmImport
      name: rws-realm-import
      namespace: iam
      jsonPointers:
        - /spec/realm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
