apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak/keycloak.yaml
  - keycloak/rws-realm.yaml
  - keycloak/ingress.yaml
  - midpoint

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: rws-keycloak-public
      namespace: iam
    path: keycloak/ingress-host-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: midpoint
      namespace: iam
    path: midpoint/ingress-host-patch.yaml
