apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg
  - keycloak/keycloak.yaml
  - keycloak/rws-realm.yaml
  - midpoint

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: iam-ingress-settings
    namespace: iam
    envs:
      - params.env

configurations:
  - kustomizeconfig/ingress-vars.yaml

vars:
  - name: INGRESS_CLASS
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: iam-ingress-settings
    fieldref:
      fieldpath: data.ingressClass
  - name: KEYCLOAK_HOST
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: iam-ingress-settings
    fieldref:
      fieldpath: data.keycloakHost
  - name: MIDPOINT_HOST
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: iam-ingress-settings
    fieldref:
      fieldpath: data.midpointHost
