apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg
  - keycloak/keycloak.yaml
  - keycloak/rws-realm.yaml
  - midpoint

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: iam-ingress-settings
    namespace: iam
    envs:
      - params.env

replacements:
  - source:
      kind: ConfigMap
      name: iam-ingress-settings
      fieldPath: data.ingressClass
    targets:
      - select:
          kind: Keycloak
          name: rws-keycloak
        fieldPaths:
          - spec.ingress.className
      - select:
          kind: Ingress
          name: midpoint
        fieldPaths:
          - spec.ingressClassName
  - source:
      kind: ConfigMap
      name: iam-ingress-settings
      fieldPath: data.keycloakHost
    targets:
      - select:
          kind: Keycloak
          name: rws-keycloak
        fieldPaths:
          - spec.hostname.hostname
  - source:
      kind: ConfigMap
      name: iam-ingress-settings
      fieldPath: data.midpointHost
    targets:
      - select:
          kind: Ingress
          name: midpoint
        fieldPaths:
          - spec.rules.0.host
