apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/${REPO_OWNER}/${REPO_NAME}
    targetRevision: main
    path: gitops/apps/platform
  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: KeycloakRealmImport
      name: rws-realm-import
      namespace: iam
      jsonPointers:
        - /spec/realm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 6
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
