name: "04 - Configure demo hosts (nip.io) & Ingresses"

on:
  workflow_dispatch:
    inputs:
      RESOURCE_GROUP:
        description: 'AKS Resource Group (from TF outputs)'
        required: true
        default: 'rwsdemo-rg'
      AKS_NAME:
        description: 'AKS cluster name (from TF outputs)'
        required: true
        default: 'rwsdemo-aks'

permissions:
  id-token: write
  contents: write

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ inputs.RESOURCE_GROUP }}
          cluster-name: ${{ inputs.AKS_NAME }}

      - name: Configure demo ingress hosts
        id: configure
        shell: bash
        run: |
          set -euo pipefail
          python3 scripts/configure_demo_hosts.py --params-file gitops/apps/iam/params.env

      - name: Commit ingress host parameters
        shell: bash
        run: |
          set -euo pipefail
          KC_HOST_VALUE="${KC_HOST:-}"
          MP_HOST_VALUE="${MP_HOST:-}"
          BRANCH_REF="${GITHUB_REF:-}"
          if git diff --quiet --exit-code -- gitops/apps/iam/params.env; then
            echo "Ingress host parameters already up to date; skipping commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add gitops/apps/iam/params.env
            git commit -m "Update demo ingress hosts to ${KC_HOST_VALUE} and ${MP_HOST_VALUE}"
            if [[ "${BRANCH_REF}" == refs/heads/* ]]; then
              BRANCH_NAME="${BRANCH_REF#refs/heads/}"
              git push origin "HEAD:${BRANCH_NAME}"
            else
              echo "Ref ${BRANCH_REF} is not a branch; skipping push."
            fi
          fi

      - name: Summary
        shell: bash
        run: |
          set -euo pipefail
          echo "✅ Done. Open these URLs in your browser:"
          echo "🔗 Keycloak : ${{ steps.configure.outputs.keycloak_url }}"
          echo "🔗 midPoint : ${{ steps.configure.outputs.midpoint_url }}"
