name: "04 - Configure demo hosts (nip.io) & Ingresses"

on:
  workflow_dispatch:
    inputs:
      RESOURCE_GROUP:
        description: 'AKS Resource Group (from TF outputs)'
        required: true
        default: 'rwsdemo-rg'
      AKS_NAME:
        description: 'AKS cluster name (from TF outputs)'
        required: true
        default: 'rwsdemo-aks'
      NAMESPACE_IAM:
        description: 'Namespace for IAM stack (Keycloak + midPoint)'
        required: true
        default: 'iam'
permissions:
  id-token: write
  contents: write

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ inputs.RESOURCE_GROUP }}
          cluster-name: ${{ inputs.AKS_NAME }}

      - name: Configure demo ingress hosts
        id: configure
        shell: bash
        env:
          NAMESPACE_IAM: ${{ inputs.NAMESPACE_IAM }}
        run: |
          set -euo pipefail
          bash scripts/configure_demo_hosts.sh update

      - name: Commit ingress host patches
        shell: bash
        run: |
          set -euo pipefail
          KC_HOST_VALUE="${KC_HOST:-}"
          MP_HOST_VALUE="${MP_HOST:-}"
          BRANCH_REF="${GITHUB_REF:-}"
          if git diff --quiet --exit-code -- k8s/apps/keycloak/hostname-patch.yaml k8s/apps/midpoint/ingress-host-patch.yaml; then
            echo "Ingress host patches already up to date; skipping commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add k8s/apps/keycloak/hostname-patch.yaml k8s/apps/midpoint/ingress-host-patch.yaml
            git commit -m "Update demo ingress hosts to ${KC_HOST_VALUE} and ${MP_HOST_VALUE}"
            if [[ "${BRANCH_REF}" == refs/heads/* ]]; then
              BRANCH_NAME="${BRANCH_REF#refs/heads/}"
              git push origin "HEAD:${BRANCH_NAME}"
            else
              echo "Ref ${BRANCH_REF} is not a branch; skipping push."
            fi
          fi

      - name: Install Argo CD CLI
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v argocd >/dev/null 2>&1; then
            curl -sSL -o /tmp/argocd-linux-amd64 \
              https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            install -m 0755 /tmp/argocd-linux-amd64 /usr/local/bin/argocd
          fi

      - name: Sync Argo CD application and verify endpoints
        shell: bash
        env:
          NAMESPACE_IAM: ${{ inputs.NAMESPACE_IAM }}
        run: |
          set -euo pipefail
          bash scripts/configure_demo_hosts.sh verify

      - name: Summary
        shell: bash
        run: |
          set -euo pipefail
          echo "✅ Done. Open these URLs in your browser:"
          echo "🔗 Keycloak : ${{ steps.configure.outputs.keycloak_url }}"
          echo "🔗 midPoint : ${{ steps.configure.outputs.midpoint_url }}"
